[build]
  base = "Frontend"
  command = "node prebuild.mjs && npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_API_URL = "/api"
  NODE_VERSION = "18"
  PYTHON_VERSION = "3.10"

[functions]
  directory = "netlify/functions"
  included_files = [
    "netlify/functions/app/**/*",
    "netlify/functions/disease_references/**/*",
    "netlify/functions/models/**/*"
  ]

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true
